codecov:
  require_ci_to_pass: yes

coverage:
  range: 40..100
  round: down
  precision: 2

  status:
    project:                   # measuring the overall project coverage
      default:
        target: auto
        # allow new commits to decrease coverage
        threshold: 4%


    patch: false                 # measuring the coverage of new changes
