codecov:
  require_ci_to_pass: yes

coverage:
  range: 20..100
  round: down
  precision: 2

  status:
    project: false                   # measuring the overall project coverage

    patch: false                 # measuring the coverage of new changes