codecov:
  require_ci_to_pass: yes

coverage:
  range: 20..100
  round: down
  precision: 2

  status:
    project:                   # measuring the overall project coverage
      default:
        target: auto
        # adjust accordingly based on how flaky your tests are
        # this allows a 5% drop from the previous base commit coverage
        threshold: 3%

    patch: no                   # measuring the coverage of new changes
